services:
  stegaformer_train:
    build: ./modules/watermarking/stegaformer
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./datasets:/app/facial_data:ro
      - ./modules/watermarking/stegaformer:/app:rw
    command: ["python", "train.py"]
    profiles: ["train-stegaformer"]

  stegaformer_watermarking:
    image: wafis-icaoeval-stegaformer_train:latest
    container_name: stegaformer_watermarking_service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./datasets:/app/facial_data:ro
      - ./experiments/output/watermarking:/app/output:rw
      - ./modules/watermarking/stegaformer:/app:rw
    entrypoint: ["python", "run_watermark.py"]
    command: "python run_watermark.py $@"
    profiles: ["inference","stegaformer"]

  facenet_recognizer:
    image: timesler/jupyter-dl-gpu:latest
    container_name: facenet_recognizer_service
    working_dir: /app
    volumes:
      - ./datasets:/app/facial_data:ro
      - ./experiments/output:/app/output:rw
      - ./modules/recognition/facenet/run_recognizer.py:/app/run_recognizer.py:ro
      - ./modules/recognition/facenet/recognizer.py:/app/recognizer.py:ro
      - ./modules/recognition/facenet/test_similarity.py:/app/test_similarity.py:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint:
    - bash
    - -c
    - |
      pip install -q facenet_pytorch scipy pandas ipython && \
      exec python run_recognizer.py "$@"
    - --
    profiles: ["facenet"]

  tensorboard_viewer:
    image: tensorflow/tensorflow:2.13.0
    ports:
      - "6006:6006"
    volumes:
      - ./modules/watermarking:/app/:rw
    working_dir: /app
    entrypoint: []
    profiles: ["tensorboard"]
    command: ["tensorboard", "--logdir", "/app", "--host", "0.0.0.0", "--port", "6006"]

  stegformer_train:
    build:
      context: ./modules/watermarking/stegformer
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./datasets:/app/facial_data:ro
      - ./modules/watermarking/stegformer:/app:rw
    entrypoint: ["python", "train.py"]
    command: "python train.py $@"
    profiles: ["train-stegformer"]

  stegformer_watermarking:
    image: wafis-icaoeval-stegformer_train:latest
    container_name: stegformer_watermarking_service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./datasets:/app/facial_data:ro
      - ./experiments/output/stegformer:/app/output:rw
      - ./modules/watermarking/stegformer:/app:rw
    entrypoint: ["python", "run_watermark.py"]
    command: "python run_watermark.py $@"
    profiles: ["inference", "stegformer"]